### ISSUE TITLE
api key not inserted to library url

### ISSUE THREAD

**Issue by Yahatix** [jweiland-net/maps2#22]
When i try to use the extension i get this in FE 
![bildschirmfoto 2017-07-24 um 16 24 58](https://user-images.githubusercontent.com/21371842/28528005-b00a3700-708c-11e7-9664-56bac70fc1ac.png)

And in the console the error: ``Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error   js?key=&callback=initMap:38 ``

Even though i entered all the keys in the BE and get the configuration in the html element 
![bildschirmfoto 2017-07-24 um 16 27 46](https://user-images.githubusercontent.com/21371842/28528133-25b05b10-708d-11e7-8cab-f867782109f1.png)

**Comment by froemken** [comment]
Hello @Yahatix 

maps2 comes with a static TypoScript Template which you have to include on your site. Please switch to Constants Editor und add the Google Maps JavaScript API Key there, too. The JavaScript API Key in Extensionmanager configuration is ONLY for the Backend. Not Frontend, as you can have multiple pagetrees with different API Keys. I know, that information is missing in documentation and will be added with one of the next versions.

Stefan

**Comment by Sonezi** [comment]
Hello, 
i tried everything and every combination on restriction in developer console, and i still getting error 
Google Maps API error: RefererNotAllowedMapError on frontend and also backend?

Any suggestion?

Thanks!!!

**Comment by froemken** [comment]
Good morning @Sonezi 

RefererNotAllowed means that your configured domain in Google Console does not match the domain where you have installed the maps2 extension.
Please sign in to Google Console and update your domain information like described here:

https://docs.typo3.org/typo3cms/extensions/maps2/2.9.1/AdministratorManual/GoogleApiKeys/Index.html

Stefan

**Comment by Sonezi** [comment]
Hello @froemken 
I tried every suggestion possible, and of course i walk-through you documentation about setting apis on developer console. :) Only way i getting working is to live unauthorized javascript key, and restrict key for geocoding authorize with my domain name. I know this is not acceptable because key remains open to everyone to use.

domain i tried are: 
http://mydomain.com/*
http://mydomain.com/typo3/*
http://*mydomain.com/*
http://www.mydomain.com/*
http://www.mydomain.com/*/*
*mydomain.com
*mydomain.com/*

Currently settings are:
geocoding: www.mydomain.com
javascript: blank no restrictions

I'am i getting wrong at anything?

Typo 8.7.7 and latest maps2

Thanks!

**Comment by froemken** [comment]
Good morning,

GeoCoding is a call from PHP. There is no referrer in its header. So Google can't know the origin domain. Please use IP based restrictions for GeoCoding.
Instead, JavaScript has a valid referrer with domain. Please add a domain based restriction to JavaScript API.
Do not add scheme (http/https) to domain. That would be an URI, not a domain. Please enter the domain only. Without all these * stars in front and end. Create entries for domain.de and www.domain.de. Create new entries for all your subdomains.
I hope you have read googles hints: Please wait until 5 minutes after saving...

Stefan

**Comment by Sonezi** [comment]
Good morning,
I followed your instructions (and waited for 5 minutes :)) for now everything is working fine.
