### ISSUE TITLE
 no @var annotation for property "extConf"

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/maps2#256]
Hi,
I use maps2 v 10.0.3. and TYPO3 10.4.24.

After upgrading to the newest version of maps2 I get these errors in log:

` Uncaught TYPO3 Exception: #1363778104: There is no @var annotation for property "extConf" in class "JWeiland\Maps2\Domain\Model\PoiCollection". | InvalidArgumentException thrown in file /var/www/vhosts/xxxxxx.my-provider.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/extbase/Classes/Validation/ValidatorResolver.php in line 157. Requested URL: https://www.my-domain.de/veranstaltungen/kalender/ort/place-name`

**Comment by froemken** [comment]
Hello @Hobokens 

I have just updated maps2 on a standalone TYPO3 10.4 without any errors. Either in sys_log not in var/log/. Last error is over a week ago. So currently I can't confirm your error.

But I have an idea:
Could it be, that you have installed maps2 version 10.0.* into a TYPO3 system running with PHP lower than 7.4? Please update PHP version to at least 7.4.

Nice greetings

Stefan

**Comment by Hobokens** [comment]
Hi @froemken,
I'm sorry, I still have the problem. My provider is JWeiland :-) and the PHP version is 7.4.2. I get this issue in frontend when I try to use the search function of events2  in list view, too.
Regards
Hobokens

**Comment by froemken** [comment]
IMO this is not a problem of maps2. The PoiCollection was called by ValidationResolver of Extbase. I remember, there were a lot of changes in Validator in the meantime. I have to debug that.
Further the validator was called from within the LocationController of events2. So, I have the possibility to remove the validator at that point. Why validating an already existing record?!?
As I call showAction of maps2 with PoiCollection domain model without any problems it's  a problem while executing an action of events2. So, I keep this issue here closed.

I you want you can copy or create a new ticket for events2.

**Comment by Hobokens** [comment]
I would be very grateful if this problem could be solved, because after updating maps2 to version 10, the way back to version 9 is no longer possible.
With many greetings
Hobokens
