### ISSUE TITLE
Call to undefined method isGoogleMapRequestAllowed

### ISSUE THREAD

**Issue by calousy** [jweiland-net/maps2#28]
I have a collection of POIs I want to show.
I get the error
"Call to undefined method JWeiland\Maps2\Service\MapService::isGoogleMapRequestAllowed()"

looks like this was introduced with 3.0.1 where isGoogleMapRequestAllowed() was removed from service but it's still in PoiCollectinViewHelper.php line 77

**Comment by froemken** [comment]
Good morning @calousy 

thank you for your help to get maps2 better. This problem was solved in current master since a week. I have just created a new release 3.0.2 and uploaded it to TER.

I have moved isGoogleMapRequestAllowed to its own GoogleRequestService now. MapService should be still possible to be loaded by ObjectManager of extbase with all its inject-methods. As we need isGoogleMapRequestAllowed while TS parsing for maps2 condition we need an inject free service.
Now we have two services. I don't really like it, but it works and we get rid of all these static method calls which helps me to build better UnitTests.

Have a good start into year 2018

Stefan
