### ISSUE TITLE
API Key is missing but is set in contstants. 

### ISSUE THREAD

**Issue by quadronet** [jweiland-net/maps2#307]
In Version 11.0 the API Key for google Maps don´t work in Backend. The key is set in the contstants. PHP 8.2, TYPO3 12.4.9

You can´t create any address without this key. 

Ok, the API Key must be set in settings for the extension. Now it works...

**Comment by sfroemkenjw** [comment]
Hello @quadronet 

yes, right.

As you're in TYPO3 backend context you don't have access to any TypoScript. That's why I needed a location to store the API key out of TypoScript context. Further we had the problem with TYPO3's multi-domain feature. We need a location for that key which is available from everywhere in backend. Since years we are using the Extension Settings. On current TYPO3 systems I'm sure we can set that key in config.yaml of site.

For FE we need the site context to make it possible to have different API keys for each site.

Stefan
