### ISSUE TITLE
Why "The ApiKeys for JavaScript APi and Geocode API can not be the same"

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/maps2#32]
I don't understand the restriction of the need of having different api keys there

**Comment by froemken** [comment]
That's easy. You can assign only one security option to an API key. For Geocode, which is domain independent, we need an IP based security. But, if we use that IP option for our JavaScript API too, that API Key can be used for all domains on a server. That's not the perfect option for shared hosting. That's why you can assign two different API Keys in our extension.

**Comment by georgringer** [comment]
I understand why you **can** use different keys, absolutely fine but why does it MUST be a different key? otherwise it throws an exception ^^

**Comment by froemken** [comment]
We have remove the check:

https://github.com/jweiland-net/maps2/commit/25dca67385bb1da570b700a7e0efabbee49f5e48#diff-506d1db559000335cb36ef355265bff3

Nice greetings from germany

Stefan
