### ISSUE TITLE
Check if API key is set in FE

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/maps2#35]
currently you do this in TS
`googleMapsForMaps2 = //maps.googleapis.com/maps/api/js?key={$plugin.tx_maps2.view.googleMapsJavaScriptApiKey}&callback=initMap`

I would like to see a warning or exception in FE if this is not set

**Comment by froemken** [comment]
This is a little bit heavy to check because:
- An integrator can define PAGE object on his own. seite = PAGE
- An integrator can set ApiKey in Setup TS directly without using Constant Editor
- An integrator can move Google Maps JS Lib to header or another TS property to include this Lib.
- PageRenderer was not filled with JS Libs at the point where I can check it.
- I can't output a FlashMessage as controllerContext was not initialized at that point. So it must be an Exception

Puh. Maybe you can check my current solution before merging it: https://github.com/jweiland-net/maps2/pull/38
Or do you have a better idea?

Stefan

**Comment by froemken** [comment]
Sorry. Maybe it would be a cool Feature for our users, but testing whole TypoScript for a missing ApiKey with each request is a little overhead. Currently I don't see any chance to integrate this feature.

We have explained how to deal with Constants Editor to set ApiKey:
https://docs.typo3.org/typo3cms/extensions/maps2/2.9.1/AdministratorManual/Installation/Index.html#preparation-include-static-typoscript

Happy holiday

Stefan
